name: production testing pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Test & Deploy Portfolio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Files Exist
      run: |
        test -f Sri-Sravan/Tic-Tac-Toe/index.html || (echo "index.html missing" && exit 1)
        test -f Sri-Sravan/Tic-Tac-Toe/style.css || (echo "style.css missing" && exit 1)
        test -f Sri-Sravan/Tic-Tac-Toe/script.js || (echo "script.js missing" && exit 1)

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: arn:aws:iam::105784982870:user/github-project
        aws-secret-access-key: AKIARRIKGXVLJ7YX574O
        aws-region: 'ap-south-1'

    - name: Deploy to S3
      run: |
        aws s3 sync Sri-Sravan/Tic-Tac-Toe/ s3://secrets.react-app-sravan  --delete
